export const mensShoesPage1 = [
    {
        "productId": 77,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l08gsy80/shoe/n/a/n/9-assg1015-9-abros-l-grey-maroon-original-imagc2m9zbzmtybx.jpeg?q=70",
        "brand": "Abros",
        "title": "ASSG1015N Running Shoes For Men",
        "color": "",
        "discountedPrice": 1455,
        "price": 1599,
        "discountPersent": 9,
        "size": ""
    },
    {
        "productId": 78,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/o/h/-original-imaggcawtbgvt7wy.jpeg?q=70",
        "brand": "asian",
        "title": "Oxygen-05 Running Shoes For Men",
        "color": "",
        "discountedPrice": 1117,
        "price": 1999,
        "discountPersent": 44,
        "size": ""
    },
    {
        "productId": 79,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/kqidx8w0/shoe/i/4/n/6-brd-406-300-blue-6-birde-blue-original-imag4g8cmfkfzkjg.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Combo Pack of 2 Sports Shoes Running Shoes For Men",
        "color": "",
        "discountedPrice": 499,
        "price": 998,
        "discountPersent": 50,
        "size": ""
    },
    {
        "productId": 80,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/g/i/g/10-rng-2021-blu-orng-44-bruton-blue-orange-original-imagdzcpzhscxwhg-bb.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 299,
        "price": 1299,
        "discountPersent": 76,
        "size": ""
    },
    {
        "productId": 81,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l4rd0280/shoe/m/d/e/6-rk-494-grey-orange-40-bruton-grey-orange-original-imagfha9ssgydnef.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Sports shoes for men | Latest Stylish Casual for men |r...",
        "color": "",
        "discountedPrice": 249,
        "price": 1299,
        "discountPersent": 80,
        "size": ""
    },
    {
        "productId": 82,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/k/k/gm1251-43-good-minar-black-original-imaft34ej4zx2z63-bb.jpeg?q=70",
        "brand": "aadi",
        "title": "Mesh |Lightweight|Comfort|Summer|Trendy|Walking|Outdoor...",
        "color": "",
        "discountedPrice": 199,
        "price": 999,
        "discountPersent": 80,
        "size": ""
    },
    {
        "productId": 83,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/kuzuoi80/shoe/2/k/x/7-brd-574-brd-575-7-birde-multicolor-original-imag7zx8epryeskm.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Trendy Sport Shoes For Men Pack Of 2 Running Shoes For ...",
        "color": "",
        "discountedPrice": 499,
        "price": 1498,
        "discountPersent": 66,
        "size": ""
    },
    {
        "productId": 84,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/1/8/p/-original-imaghvb7kkpy73vn.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 249,
        "price": 1299,
        "discountPersent": 80,
        "size": ""
    },
    {
        "productId": 85,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/q/r/j/-original-imagzjg25cg9wsrj.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "MIKE (N) Running Shoes For Men",
        "color": "",
        "discountedPrice": 949,
        "price": 1699,
        "discountPersent": 44,
        "size": ""
    },
    {
        "productId": 86,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/p/l/8-9326-8-world-wear-footwear-yellow-original-imagmengqep9gbwu.jpeg?q=70",
        "brand": "World Wear Footwear",
        "title": "Affordable Range of Stylish Casual Walking Comfortable ...",
        "color": "",
        "discountedPrice": 249,
        "price": 998,
        "discountPersent": 75,
        "size": ""
    },
    {
        "productId": 87,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/1/s/j/8-east-8-jqr-l-gry-original-imagjueg2zfewfpg.jpeg?q=70",
        "brand": "JQR",
        "title": "EAST COOLSENSE lightweight, trenndy stylish,strechable,...",
        "color": "",
        "discountedPrice": 811,
        "price": 1249,
        "discountPersent": 35,
        "size": ""
    },
    {
        "productId": 88,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/s/j/9/-original-imaghvrfzmsz9e6kh.jpeg?q=70",
        "brand": "NIVIA",
        "title": "Super Court 2.0 Badminton Shoes For Men",
        "color": "",
        "discountedPrice": 1047,
        "price": 1999,
        "discountPersent": 47,
        "size": ""
    },
    {
        "productId": 89,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l4oi4cw0/shoe/g/u/e/6-blk-482-40-bruton-black-red-original-imagfgp97vzhyne2.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 249,
        "price": 1299,
        "discountPersent": 80,
        "size": ""
    },
    {
        "productId": 90,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l0igvww0/shoe/j/x/z/7-brd-678-7-birde-blue-original-imagca7bcj6p99gw.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Stylish Comfortable Lightweight, Breathable Black Runni...",
        "color": "",
        "discountedPrice": 299,
        "price": 999,
        "discountPersent": 70,
        "size": ""
    },
    {
        "productId": 91,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/i/k/r/-original-imaghugwugwyczwc.jpeg?q=70",
        "brand": "asian",
        "title": "Future-01 running shoes For Men",
        "color": "",
        "discountedPrice": 514,
        "price": 999,
        "discountPersent": 48,
        "size": ""
    },
    {
        "productId": 92,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/r/j/c/-original-imaghvb8a8hjrfmr.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "STREET-RUN Running Shoes For Men",
        "color": "",
        "discountedPrice": 1329,
        "price": 1799,
        "discountPersent": 26,
        "size": ""
    },
    {
        "productId": 93,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/9/h/e/10-bd-1191bl-10-nivia-blue-original-imagndzhu9sgpyzf.jpeg?q=70",
        "brand": "NIVIA",
        "title": "Badminton Shoes For Men",
        "color": "",
        "discountedPrice": 896,
        "price": 1120,
        "discountPersent": 20,
        "size": ""
    },
    {
        "productId": 94,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/h/e/7-rng-2cmb-2031-551-41-bruton-blue-white-original-imaggameyhax2hwu.jpeg?q=70",
        "brand": "BRUTON",
        "title": "omboPack of-2 | sports shoes for men |walking, gym, tre...",
        "color": "",
        "discountedPrice": 499,
        "price": 2499,
        "discountPersent": 80,
        "size": ""
    },
    {
        "productId": 95,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/r/j/e/-original-imagmuc8gfb7heya.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "HURRICANE Running Shoes For Men",
        "color": "",
        "discountedPrice": 1054,
        "price": 1299,
        "discountPersent": 18,
        "size": ""
    },
    {
        "productId": 96,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/1/e/a/-original-imaghvb5mhwjjasb.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 299,
        "price": 1299,
        "discountPersent": 76,
        "size": ""
    },
    {
        "productId": 97,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/6/0/r/10-cb-fast-white-rocky-black-10-sfr-multicolor-original-imagmgsbundpa9at.jpeg?q=70",
        "brand": "SFR",
        "title": "FAST Trenddy Tainer Lace-ups Sporty Casuals Running Sho...",
        "color": "",
        "discountedPrice": 489,
        "price": 1699,
        "discountPersent": 71,
        "size": ""
    },
    {
        "productId": 98,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l1jmc280/shoe/m/y/z/6-innova-04cwhtsky-asian-white-original-imagd3atfhw3tdwh.jpeg?q=70",
        "brand": "asian",
        "title": "Running Shoes For Men",
        "color": "",
        "discountedPrice": 1099,
        "price": 1999,
        "discountPersent": 45,
        "size": ""
    },
    {
        "productId": 99,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/ky1vl3k0/shoe/z/b/j/8-cosco-tan-density-tan-original-imagaderx2s5znkj.jpeg?q=70",
        "brand": "density",
        "title": "COSCO Training & Gym Shoes For Men",
        "color": "",
        "discountedPrice": 399,
        "price": 999,
        "discountPersent": 60,
        "size": ""
    },
    {
        "productId": 100,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/z/l/6-ori-9010-6-bersache-red-original-imagn69etxggadch.jpeg?q=70",
        "brand": "BERSACHE",
        "title": "Bersache Sports Shoes For Men|Red For Running,Walking,g...",
        "color": "",
        "discountedPrice": 649,
        "price": 3842,
        "discountPersent": 83,
        "size": ""
    },
    {
        "productId": 101,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/l/n/4/-original-imaghvb4ew3j5x9v.jpeg?q=70",
        "brand": "ASE",
        "title": "Durable Performance Cricket Shoes with Dual Closure, La...",
        "color": "",
        "discountedPrice": 939,
        "price": 2250,
        "discountPersent": 58,
        "size": ""
    },
    {
        "productId": 102,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/n/2/oxygen-4-airdron-white-navy-original-imafywywmhjcsyhy-bb.jpeg?q=70",
        "brand": "AIRDRON",
        "title": "Oxygen Running Shoes For Men",
        "color": "",
        "discountedPrice": 494,
        "price": 1499,
        "discountPersent": 67,
        "size": ""
    },
    {
        "productId": 103,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/x/q/9-chrome-01-asian-white-original-imaggaz54tgkqyq6.jpeg?q=70",
        "brand": "asian",
        "title": "Chrome-01 White Sports,Casual,Walking,Stylish Running S...",
        "color": "",
        "discountedPrice": 1299,
        "price": 2299,
        "discountPersent": 43,
        "size": ""
    },
    {
        "productId": 104,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/r/r/-original-imaghsggbdxpvs9c.jpeg?q=70",
        "brand": "NIVIA",
        "title": "Ace Walking Shoes For Men",
        "color": "",
        "discountedPrice": 1199,
        "price": 2399,
        "discountPersent": 50,
        "size": ""
    },
    {
        "productId": 105,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/s/i/l/10-2031-blu-wht-44-bruton-blue-original-imagfmdubtgj8ebj-bb.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Running Shoes Running Shoes For Men",
        "color": "",
        "discountedPrice": 349,
        "price": 1299,
        "discountPersent": 73,
        "size": ""
    },
    {
        "productId": 106,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/m/z/-original-imagg7t26zdugnx8.jpeg?q=70",
        "brand": "KILLER",
        "title": "22509-T. Blue Phylon Running Shoes For Men",
        "color": "",
        "discountedPrice": 976,
        "price": 2499,
        "discountPersent": 60,
        "size": ""
    },
    {
        "productId": 107,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/u/7/-original-imagg6rc839zxhw4.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "NORTH PLUS Running Shoes For Men",
        "color": "",
        "discountedPrice": 1299,
        "price": 1699,
        "discountPersent": 23,
        "size": ""
    },
    {
        "productId": 108,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/y/i/n/7-brd-911-7-birde-navy-original-imaghq8zakm4mmgn.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Premium Navy Sports Shoes For Men Walking Shoes For Men",
        "color": "",
        "discountedPrice": 715,
        "price": 1999,
        "discountPersent": 64,
        "size": ""
    },
    {
        "productId": 109,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/u/z/q/-original-imagn24jy9bnpjsn.jpeg?q=70",
        "brand": "Reebok",
        "title": "Propulsion 2.0 M Running Shoes For Men",
        "color": "",
        "discountedPrice": 1199,
        "price": 2799,
        "discountPersent": 57,
        "size": ""
    },
    {
        "productId": 110,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/krz97rk0/shoe/p/w/8/11-54610-12-skechers-nvgy-original-imag5n6rkkmrhtqf.jpeg?q=70",
        "brand": "Skechers",
        "title": "Go Walk Max-Precision Walking Shoes For Men",
        "color": "",
        "discountedPrice": 2657,
        "price": 5299,
        "discountPersent": 49,
        "size": ""
    },
    {
        "productId": 111,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/v/e/6-rng-512-black-40-bruton-black-original-imagexnpgzqzzbze-bb.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 299,
        "price": 1299,
        "discountPersent": 76,
        "size": ""
    },
    {
        "productId": 112,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/knt7zbk0/shoe/m/r/r/7-5g-845-campus-gry-d-gry-original-imag2eynkpzvz6tf.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "MIKE (N) Running Shoes For Men",
        "color": "",
        "discountedPrice": 942,
        "price": 1699,
        "discountPersent": 44,
        "size": ""
    },
    {
        "productId": 113,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/s/9/k/-original-imagg6r6yveqfsw9.jpeg?q=70",
        "brand": "Asics",
        "title": "GEL-CONTEND 4B Running Shoes For Men",
        "color": "",
        "discountedPrice": 1693,
        "price": 3999,
        "discountPersent": 57,
        "size": ""
    },
    {
        "productId": 114,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/k6fd47k0pkrrdj/shoe/x/g/s/9-cdnyafqbdq-world-wear-footwear-original-imafzrkveuhdgdy7.jpeg?q=70",
        "brand": "World Wear Footwear",
        "title": "Combo Pack of 2 Latest Collection Stylish casual Sports...",
        "color": "",
        "discountedPrice": 399,
        "price": 998,
        "discountPersent": 60,
        "size": ""
    },
    {
        "productId": 115,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/ksxjs7k0/shoe/o/g/7/9-6g-842-campus-blk-n-org-original-imag6dzwz7hdwgxh.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "HURRICANE Running Shoes For Men",
        "color": "",
        "discountedPrice": 759,
        "price": 1299,
        "discountPersent": 41,
        "size": ""
    },
    {
        "productId": 116,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/kzblocw0/shoe/l/i/f/9-crystal-13cblkrd-asian-black-original-imagbdaykm9wfnmz.jpeg?q=70",
        "brand": "asian",
        "title": "Crystal-13 Black Sports Transparent Sole Technology For...",
        "color": "",
        "discountedPrice": 1259,
        "price": 2299,
        "discountPersent": 45,
        "size": ""
    }
];